FROM maven:3.5.3-jdk-8

# Create and use a custom directory for the application
WORKDIR app

# Copy the src code into the app directory of the image
COPY src/* ./

# Build the java app with maven
RUN mvn -B -DskipTests clean package

# Run the app?
#CMD [ "npm", "start" ]
