FROM node:9-alpine

# Install Docker and dependencies - The build environment needs to be able to create images, so docker binary needed.
RUN apk --update add \
  bash \
  iptables \
  ca-certificates \
  e2fsprogs \
  docker \
  && rm -rf /var/cache/apk/*
